version: '3.7'

services:
  consul:
    image: hashicorp/consul-template:0.20.0-alpine
    volumes:
    - ./alertmanager.ctmpl:/consul-template/config/alertmanager.ctmpl
    - data:/consul-template/data
    environment:
      ALERTMANAGERPREFIX: alertmanager
    command:
    -  consul-template
    - -consul-addr=127.0.0.1:8500
    - -template
    - "/consul-template/config/alertmanager.ctmpl:/consul-template/data/alertmanager.json:curl -X POST http://alertmanager:9093/-/reload"
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.18.0
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
    - data:/etc/alertmanager
    command:
    - "--config.file=/etc/alertmanager/alertmanager.json"
    - "--storage.path=/alertmanager"
    depends_on:
    - consul
    restart: always

  
volumes:
  data: