version: "3.7"

services:
  coredns:
    image: coredns/coredns:1.6.5
    volumes:
    - "./config/Corefile:/etc/coredns/Corefile"
    command:
    - -conf
    - /etc/coredns/Corefile
    # - -dns.port
    # - "1053"
    ports:
    - "1053:53/tcp"
    - "1053:53/udp"