version: '3.3'
volumes:
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 123
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
    - grafana_data:/var/lib/grafana
    ports:
    - "3000:3000"
