version: '3.3'
services:
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 123
      # GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
    - "3000:3000"