version: '3'
volumes:
    consul_data:

services:
    consul:
      image: consul:1.5.2
      environment:
      - CONSUL_BIND_INTERFACE=eth0
      command:
      - 'agent'
      - '-server'
      - '-bootstrap-expect'
      - '1'
      - '-ui'
      - '-client'
      - '0.0.0.0'
      ports:
      - '8500:8500' 
      volumes:
      - 'consul_data:/consul/data'