version: "3.7"

services:
  coordination:
    image: 00arthur00/elasticsearch-ik:7.5.1
    # healthcheck:
    #   test: curl -fs http://localhost:9200/_cat/health || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 45s
    configs:
      - source: es-coordination
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options-coordination
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - esnet
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        # mode: host
    deploy:
      # endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 3
      resources:
        limits:
          memory: 4G

  master1:
    image:  00arthur00/elasticsearch-ik:7.5.1
    # healthcheck:
    #   test: curl -fs http://localhost:9200/_cat/health || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 45s
    environment:
      node.name: es-master1
    configs:
      - source: es-master
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options-master
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - esnet
    volumes:
      - esmaster1:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [ node.labels.umb.es.master1 == true ]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 4G

  master2:
    image:  00arthur00/elasticsearch-ik:7.5.1
    # healthcheck:
    #   test: curl -fs http://localhost:9200/_cat/health || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 45s
    environment:
      node.name: es-master2
    configs:
      - source: es-master
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options-master
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - esnet
    volumes:
      - esmaster2:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [ node.labels.umb.es.master2 == true ]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 4G

  master3:
    image:  00arthur00/elasticsearch-ik:7.5.1
    # healthcheck:
    #   test: curl -fs http://localhost:9200/_cat/health || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 45s
    environment:
      node.name: es-master3
    configs:
      - source: es-master
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options-master
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - esnet
    volumes:
      - esmaster3:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [ node.labels.umb.es.master3 == true ]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 4G

  data1:
    image:  00arthur00/elasticsearch-ik:7.5.1
    # healthcheck:
    #   test: curl -fs http://localhost:9200/_cat/health || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 45s
    environment:
      node.name: es-data1
    configs:
      - source: es-data
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options-data
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - esnet
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [ node.labels.umb.es.data1 == true ]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 16G
  data2:
    image:  00arthur00/elasticsearch-ik:7.5.1
    # healthcheck:
    #   test: curl -fs http://localhost:9200/_cat/health || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 45s
    environment:
      node.name: es-data2
    configs:
      - source: es-data
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options-data
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - esnet
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [ node.labels.umb.es.data2 == true ]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 16G
  data3:
    image:  00arthur00/elasticsearch-ik:7.5.1
    # healthcheck:
    #   test: curl -fs http://localhost:9200/_cat/health || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 45s
    environment:
      node.name: es-data3
    configs:
      - source: es-data
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: jvm-options-data
        target: /usr/share/elasticsearch/config/jvm.options
    networks:
      - esnet
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [ node.labels.umb.es.data3 == true ]
      endpoint_mode: dnsrr
      mode: "replicated"
      replicas: 1
      resources:
        limits:
          memory: 16G
  kibana:
    image: registry.corp.ucarinc.com/umonibench/kibana:7.5.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://data1:9200
    networks:
      - esnet
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

networks:
  esnet:
    driver: overlay
    attachable: true
    name: esnet

volumes:
  esmaster1:
  esmaster2:
  esmaster3:

  esdata1:
  esdata2:
  esdata3:

configs:
  es-coordination:
    name: es-coordination
    file: es-config/es-coordination.yml
  es-master:
    name: es-master
    file: es-config/es-master.yml

  es-data:
    name: es-data
    file: es-config/es-data.yml


  jvm-options-coordination:
    name: jvm-options-coordination
    file: es-config/jvm.coordination.options
  jvm-options-data:
    name: jvm-options-data 
    file: es-config/jvm.data.options
  jvm-options-master:
    name: jvm-options-master
    file: es-config/jvm.master.options
