version: '3.3'
services:
  nginx:
    image: openresty/openresty:centos-rpm
    ports:
    - "8018:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./access.log:/data/nginx/1.14.1/logs/web1/access.log
  app:
    image: python
    command: python -m http.server
  app2:
    image: python
    command: python -m http.server