version: '3.3'
services:
  prometheus:
    image: prom/prometheus:v2.11.1
    command:
    - --web.enable-lifecycle
    - --web.external-url=http://localhost:9090
    - --config.file=/etc/prometheus/prometheus.yml
    - --log.level=debug
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
    - "9090:9090"
  blackbox_exporter:
    image: prom/blackbox-exporter
    volumes: 
    - "./config/blackbox.yml:/config/blackbox.yml"
    ports:
    - "9115:9115"
    command: 
    - --config.file=/config/blackbox.yml
