# my global config
global:
  scrape_interval:     10h # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 3s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  scrape_timeout: 3s

# Alertmanager configuration
# with thanos rule, we don't need to contains the alertmanager configration in prometheus


scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [icmp_ipv4]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - 127.0.0.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.99.57.47:9115  # The blackbox exporter's real hostname:port.