version: "3.7"
services:
  swagger-editor:
    image: "swaggerapi/swagger-editor"
    ports:
    - "8080:8080"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

