global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: web.hook
  group_by:
  - job
  - alertname
  group_wait: 0s
  group_interval: 1m
  repeat_interval: 30s
  routes:
  - match:
      job: "prometheus" 
    group_wait: 0s
    group_interval: 5m
    repeat_interval: 6h


inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - job
  - instance
receivers:
- name: web.hook
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://webhookprinter:8000

templates:
- default.tmpl
