version: '3.3'
services:
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:ro"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    - "/dev/disk/:/dev/disk:ro"
    ports:
    - "8080:8080"
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.15.2
    volumes: 
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
    - "9093:9093"  
  prometheus:
    image: prom/prometheus:v2.6.0
    container_name: prometheus
    command: --web.enable-lifecycle --web.external-url=http://localhost:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./rule:/prometheus/rule/
    ports: 
    - "9090:9090"
    depends_on:
    - alertmanager

  webhookprinter:
    container_name: webhookprinter
    image: 00arthur00/webhookprinter  
  alertPrinter:
    image: 00arthur00/webhookprinter