version: '2.4'

services:

  consul-agent-1: 
    image: consul:latest
    environment:
    - CONSUL_BIND_INTERFACE=eth0
    networks:
      consul-dc1:
        ipv4_address: 10.0.1.3
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  # consul-agent-2:
  #   <<: *consul-agent

  # consul-agent-3:
  #   <<: *consul-agent

  consul-server-1: 
    image: consul:latest
    environment:
    - CONSUL_BIND_INTERFACE=eth0
    networks: 
      consul-dc1:
        ipv4_address: 10.0.1.11
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0 -advertise-wan=10.0.1.11"

  consul-server-2:
    image: consul:latest
    environment:
    - CONSUL_BIND_INTERFACE=eth0
    networks: 
      consul-dc1:
        ipv4_address: 10.0.1.12
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0 -advertise-wan=10.0.1.12"

  consul-server-bootstrap:
    image: consul:latest
    environment:
    - CONSUL_BIND_INTERFACE=eth0
    networks: 
      consul-dc1:
        ipv4_address: 10.0.1.13
    ports:
      - "8501:8500"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0 -datacenter dc1  -retry-join-wan 10.0.2.13 -advertise-wan=10.0.1.13"

networks:
  consul-dc1:
    ipam:
      driver: default
      config:
      - subnet: "10.0.1.0/24"