version: "3.1"

volumes:
  prometheus1_data: {}
  grafana_data: {}

services:
  prometheus-1:
    image: prom/prometheus:v2.13.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus1_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus1.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.max-block-duration=2h"
      - "--storage.tsdb.min-block-duration=2h"
      - "--web.enable-lifecycle"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9081:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    restart: always

  thanos-sidecar-1:
    image: thanosio/thanos:v0.8.1
    volumes:
      - ./thanos/:/etc/thanos/
      - prometheus1_data:/prometheus
    command:
      - "sidecar"
      - "--tsdb.path=/prometheus"
      - "--prometheus.url=http://prometheus-1:9090"
      - "--grpc-address=0.0.0.0:10091"
      - "--http-address=0.0.0.0:10902"
      - "--objstore.config-file=/etc/thanos/bucket_config.yaml"
    depends_on:
      - prometheus-1
    restart: always

  thanos-querier:
    image: thanosio/thanos:v0.8.1
    command:
      - "query"
      - "--grpc-address=0.0.0.0:10091"
      - "--http-address=0.0.0.0:10902"
      - "--query.replica-label=replica"
      - "--store=thanos-sidecar-1:10091"
    ports:
      - 10902:10902
    depends_on:
      - thanos-sidecar-1
    restart: always

  thanos-ruler:
    image: thanosio/thanos:v0.8.1
    volumes:
      - ./thanos/:/etc/thanos/
    command:
      - "rule"
      - "--grpc-address=0.0.0.0:10091"
      - "--http-address=0.0.0.0:10902"
      - "--log.level=debug"
      - "--data-dir=/data"
      - "--eval-interval=15s"
      - "--rule-file=/etc/thanos/*.rules.yaml"
      - "--alertmanagers.url=http://alertmanager:9093"
      - "--query=thanos-querier:10902"
      - "--objstore.config-file=/etc/thanos/bucket_config.yaml"
      - '--label=ruler_cluster="vegas"'
      - '--label=ruler_replica="r1"'
    ports:
      - 10903:10902
    depends_on:
      - thanos-querier
    restart: always

  node-exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.19.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yaml"
      - "--storage.path=/alertmanager"
  cadvisor:
    image: google/cadvisor:v0.33.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always

  grafana:
    image: grafana/grafana:6.4.2
    user: "104"
    depends_on:
      - prometheus-1
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
