version: '2.2'
services:
  influxdb:
    image: influxdb:1.7.8
    ports:
    - "8086:8086"
    - "8083:8083"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: "prometheus"
    volumes: 
    - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/'
    